name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or master if you're using the default branch

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js (if you're using Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # change based on your node version

    - name: Install dependencies (Node.js example)
      run: npm install  # use pip install if you're using Python

    - name: Run tests (Optional)
      run: npm test  # skip this if you don't have tests

    # Deploy to Azure
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: hithubapp  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .  # You can specify the path to the directory if needed
